# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: apply-on-merge

on:   
  push:
    branches:
      - main

jobs:
  apply: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -k cloud/w9/day-a/k8s