apiVersion: v1
kind: Service
metadata:
  name: k8s-local-lab
  labels:
    app: k8s-local-lab
    component: api
spec:
  type: ClusterIP
  selector:
    app: k8s-local-lab
    component: api
  ports:
    - name: http
      port: 80
      targetPort: 3000
