apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - templates/disallow-latest-tag.yaml
  - templates/require-limits.yaml
  - templates/disallow-root-user.yaml
  - templates/disallow-host-network.yaml
  - templates/limit-replicas.yaml
  - constraints/disallow-latest-tag.yaml
  - constraints/require-limits.yaml
  - constraints/disallow-root-user.yaml
  - constraints/disallow-host-network.yaml
  - constraints/limit-replicas.yaml