# Sigstore Policy Controller admission policy.
# Public key reused from W10 Day B key-based signing lab.
apiVersion: policy.sigstore.dev/v1beta1
kind: ClusterImagePolicy
metadata:
  name: w10-api-must-be-signed
spec:
  images:
    - glob: ghcr.io/g-03-xbrain-phase-2/w10-api*
  authorities:
    - key:
        data: |
          -----BEGIN PUBLIC KEY-----
          MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEv+kb4wg8kexlh5hSs4fS9U+olSSI
          aS1BDcaw7iSu3ClA9zeQdkZr9YtuVqdZOsQP15q0nQQC0KJ2+5js6ttACA==
          -----END PUBLIC KEY-----
