apiVersion: v1
kind: Pod
metadata:
    name: k8s-local-lab-pod
    labels:
        app: k8s-local-lab
        version: v1
spec:
    containers:
        - name: app
          image: k8s-local-lab:v1
          imagePullPolicy: Never
          ports:
              - containerPort: 3000
