# ExternalSecret -> map key AWS Secrets Manager vào Kubernetes Secret.
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app-db-secret
  namespace: demo
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: aws-store
    kind: SecretStore
  target:
    name: app-db-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_USERNAME
      remoteRef:
        key: w10/lab/demo/app
        property: username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: w10/lab/demo/app
        property: password
