apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-email-secret
  namespace: argocd-test
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
stringData:
  smtp-password: "CHANGE_ME_DO_NOT_USE_IN_PROD"
