apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: backend
  namespace: argocd-test
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  replicas: 4
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: argocd-test-backend:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          envFrom:
            - configMapRef:
                name: backend-config
          env:
            - name: ERROR_RATE
              value: "0.8"
            - name: VERSION
              value: v2-bad
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
  strategy:
    canary:
      steps:
        - setWeight: 25
        - analysis:
            templates:
              - templateName: backend-error-rate
        - setWeight: 50
        - analysis:
            templates:
              - templateName: backend-error-rate
        - setWeight: 100
