apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: argocd-test
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: argocd-test-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
