apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-reader
  namespace: w10-day-b
  labels:
    app: secret-reader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-reader
  template:
    metadata:
      labels:
        app: secret-reader
    spec:
      containers:
      - name: secret-reader
        image: busybox:1.36
        command:
          - /bin/sh
          - -c
          - |
            while true; do
                echo "---- $(date) ----"
                echo "DB_USERNAME=$(cat /etc/app-secrets/DB_USERNAME 2>/dev/null || true)"
                echo "DB_PASSWORD=$(cat /etc/app-secrets/DB_PASSWORD 2>/dev/null || true)"
                sleep 10
              done
        volumeMounts:
          - mountPath: /etc/app-secrets
            name: app-db-secret
            readOnly: true
        resources:
          requests:
              cpu: 10m
              memory: 16Mi
          limits:
            cpu: 50m
            memory: 64Mi
      volumes:
        - name: app-db-secret
          secret:
            secretName: app-db-secret
    